version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inventario_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventario_master
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario_app
    restart: unless-stopped
    ports:
      - "80:3000" # Mapea el puerto 80 del servidor al 3000 del contenedor
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/inventario_master?schema=public
      - NEXTAUTH_SECRET=mi-secreto-para-produccion-muy-seguro-123
      # IMPORTANTE: Cambiar localhost por la IP o Dominio de tu servidor en producción
      - NEXTAUTH_URL=http://localhost 
    depends_on:
      - db

volumes:
  pgdata:
