version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inventario_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_inventario
      POSTGRES_PASSWORD: "SecureDB_Inv_2026!#"
      POSTGRES_DB: inventario_master_db
    # Removido el mapeo de puertos 5432:5432 hacia el host para evitar conflictos con otros proyectos haci para tener mayor escalabilidad
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario_app
    restart: unless-stopped
    ports:
      # Puerto 8080 asignado especificamente a este proyecto para no chocar con el puerto 80
      - "8080:3000"
    environment:
      - DATABASE_URL=postgresql://admin_inventario:SecureDB_Inv_2026!%23@db:5432/inventario_master_db?schema=public
      - NEXTAUTH_SECRET=b7d38392f9e42b6a1c8f0e5d4a9b2c7e8f1d3a6c9e0b4f5a
      # URL actualizada con el puerto 8080
      - NEXTAUTH_URL=http://Rengifo_Ltda:8080
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
    depends_on:
      - db

volumes:
  pgdata:

