version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inventario_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_inventario
      POSTGRES_PASSWORD: "SecureDB_Inv_2026!#"
      POSTGRES_DB: inventario_master_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario_app
    restart: unless-stopped
    ports:
      - "80:3000" # Mapea el puerto 80 del servidor al 3000 del contenedor
    environment:
      - DATABASE_URL=postgresql://admin_inventario:SecureDB_Inv_2026!%23@db:5432/inventario_master_db?schema=public
      - NEXTAUTH_SECRET=b7d38392f9e42b6a1c8f0e5d4a9b2c7e8f1d3a6c9e0b4f5a
      # IMPORTANTE: Cambiar localhost por la IP o Dominio de tu servidor en producción
      - NEXTAUTH_URL=http://localhost 
    depends_on:
      - db

volumes:
  pgdata:
